load_module modules/ngx_http_js_module.so;

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    js_import utils from headers.js;
    js_set $all_headers utils.list_headers;

    log_format json_access escape=none '{'
        '"time": "$time_iso8601",'
        '"level": "INFO",'
        '"status": "$status",'
        '"method": "$request_method",'
        '"addr": "$remote_addr",'
        '"uri": "$request_uri",'
        '"headers": $all_headers,'
        '"epoch": $msec'
    '}';

    access_log  /var/log/nginx/access.log  json_access;

    sendfile  on;

    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;
}
